### ISSUE TITLE
How to run staticcheck for repo with submodules?

### ISSUE THREAD

**Issue by fogfish** [dominikh/staticcheck-action#11]
Let's imagine we have repo with submodules (similar to aws-sdk-v2)
```
repo
|
+-- modA
|      +-- go.mod
+-- modB
       +-- go.mod
```

staticcheck fails
```
staticcheck ./...
-: pattern ./...: directory prefix . does not contain modules listed in go.work or their selected dependencies (compile)
```

It is all good, you can run
```
staticcheck ./modA/...
staticcheck ./modB/...
```

but you cannot make it with GitHub actions. The only option to use matrix but it spawn too many job. It would be handy to run a single job to test all submodules.

```
jobs:

  code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["modA", "modB"]
    steps:

      - uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - uses: actions/checkout@v3

      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          install-go: false
          working-directory: ${{ matrix.module }}
```
