### ISSUE TITLE
statichcheck built with older version 

### ISSUE THREAD

**Issue by amir20** [dominikh/staticcheck-action#17]
Hello, 

Sorry if this question has been asked before. I did a little search and couldn't find anything. I have this issue for a while and somehow just ignored it. 

I recently updated to latest version of Go. However, when using `staticcheck-action` I get: 

```
Run dominikh/staticcheck-action@v1.3.1
Run WillAbides/setup-go-faster@v1.14.0
Run src/run
/opt/hostedtoolcache/go/1.23.2/x64 already exists
Run actions/cache@v4
Cache Size: ~76 MB (800486[9](https://github.com/amir20/dozzle/actions/runs/11766917251/job/32775030570#step:4:10)1 B)
/usr/bin/tar -xf /home/runner/work/_temp/d[12](https://github.com/amir20/dozzle/actions/runs/11766917251/job/32775030570#step:4:14)ad631-7e6f-41c8-90e4-1f2ed71d0443/cache.tzst -P -C /home/runner/work/dozzle/dozzle --use-compress-program unzstd
Received 80048691 of 80048691 (100.0%), 76.3 MBs/sec
Cache restored successfully
Cache restored from key: staticcheck-Linux--596861412d[21](https://github.com/amir20/dozzle/actions/runs/11766917251/job/32775030570#step:4:24)0a293a4245aee86e22a1e7e10da6
Run export STATICCHECK_CACHE="/home/runner/work/_temp/staticcheck"
go: downloading honnef.co/go/tools v0.5.1
go: downloading golang.org/x/tools v0.21.1-0.20240531212143-b6235391adb3
go: downloading github.com/BurntSushi/toml v1.4.1-0.202405261936[22](https://github.com/amir20/dozzle/actions/runs/11766917251/job/32775030570#step:4:25)-a339e1f7089c
go: downloading golang.org/x/exp/typeparams v0.0.0-20231108232855-2478ac86f678
go: downloading golang.org/x/sync v0.7.0
go: downloading golang.org/x/mod v0.17.0
go: downloading golang.org/x/exp v0.0.0-20231110203233-9a3e60[36](https://github.com/amir20/dozzle/actions/runs/11766917251/job/32775030570#step:4:40)ecaa
go: downloading go1.23.3 (linux/amd64)
-: module requires at least go1.23.3, but Staticcheck was built with go1.23.2 (compile)
Error: Process completed with exit code 1.
```

My configuration is 

```
 staticcheck:
    runs-on: ubuntu-latest
    name: Go Staticcheck
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate dependencies
        run: make fake_assets shared_key.pem shared_cert.pem
      - name: Stactic checker
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "latest"
```

You can see "go: downloading go1.23.3 (linux/amd64)" above. So it looks like it has downloaded latest version. 

But I am not sure how to make Statichcheck use the latest version of Go. 

Thanks!
