### ISSUE TITLE
Broken with `(unsupported version: 2)` error  if using staticcheck v2024.1.1

### ISSUE THREAD

**Issue by jcsalem** [dominikh/staticcheck-action#18]
When running this action, I now get errors like:
```
-: internal error in importing "internal/byteorder" (unsupported version: 2); please report an issue (compile)
-: internal error in importing "internal/cpu" (unsupported version: 2); please report an issue (compile)
-: internal error in importing "internal/goarch" (unsupported version: 2); please report an issue (compile)
-: internal error in importing "internal/goos" (unsupported version: 2); please report an issue (compile)
-: internal error in importing "math/bits" (unsupported version: 2); please report an issue (compile)
```
when using staticcheck version 2024.1.1 with the recently released Go 1.24

Here's a snippet of the workflow that reproduces this:
```
     - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2024.1.1"
```

I think (not sure) it can be fixed by removing the specific version name. 

More detail on this error can be found here: https://github.com/dominikh/go-tools/issues/1627
