### ISSUE TITLE
Options to modify cache

### ISSUE THREAD

**Issue by shivam-ajmera** [dominikh/staticcheck-action#19]
Hi, trying to understand how the github cache action works and specifically for this staticcheck.

I see we cache for each commit but is this necessary? Majority of the runs are hit via the restore-key because unique git sha. However, the post run ends up saving the cache. Running into Github's 10 GB cache warnings. Maybe worth tying the cache key to the go.sum or something else that can be used across commits/branches? Example - for setup-go most people create a cache only on main and let other commits only read from this cache.

Or could we have the option to disable it then? 

```
 - uses: actions/cache@v4
      if: ${{ inputs.merge-files == '' }}
      with:
        path: |
          ${{ runner.temp }}/staticcheck
          ${{ inputs.install-go != 'false' && steps.install_go.outputs.GOCACHE || '' }}
        # use a unique cache key for storing, then restore from the newest cache entry we can.
        key: staticcheck-${{ runner.os }}-${{ inputs.cache-key }}-${{ github.sha }}
        restore-keys: |
          staticcheck-${{ runner.os }}-${{ inputs.cache-key }}-
```

Happy to open a PR for whichever direction makes sense!
