### ISSUE TITLE
support `~` operator for generic since go1.18

### ISSUE THREAD

**Issue by kuchaguangjie** [dominikh/staticcheck-action#6]
When run the github action, get errors like:
> Error: ../../../go/pkg/mod/github.com/life4/genesis@v1.1.0/constraints/constraints.go:13:2: illegal character U+007E '~' (compile)

The source code is:
```
type Signed interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64
}
```

Which is a valid go generic syntax, since go1.18.

Here is the snippet of github action job:
```
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        go: [ "1.18.x" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
```

I've setup go 1.18, and in `sragegy` specify `1.18.x`.

Is this a bug? Of do I've to chagne github action config to fix that? Thanks.

**Comment by dominikh** [comment]
Set `staticcheck-action`'s `install-go` option to false to use the version of Go you've manually installed with `actions/setup-go`.

**Comment by kuchaguangjie** [comment]
Ok, now it works.

The step looks like this now:
```
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          install-go: false
```
